-- Profil recruteur (entreprise), lié au compte utilisateur après vérification email.
-- À exécuter sur la base Supabase / Postgres (une fois).

CREATE TABLE IF NOT EXISTS recruteurs (
  id                integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id           integer NOT NULL UNIQUE REFERENCES users (id) ON DELETE CASCADE,
  nom_societe       varchar(255),
  nom_contact       varchar(255),
  telephone         varchar(50),
  email_personnel   varchar(255),
  email_pro         varchar(255),
  ice               varchar(50),
  adresse           text,
  created_at        timestamptz NOT NULL DEFAULT now(),
  updated_at        timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS recruteurs_user_id_idx ON recruteurs (user_id);

COMMENT ON TABLE recruteurs IS 'Informations entreprise / contact pour les comptes recruteur (onboarding post-inscription).';
